### ISSUE TITLE
【BUG】Windows端读取出现问题

### ISSUE THREAD

**Issue by SDCOM-0415** [oneclickvirt/ecs#1]
**问题出现情况**
1.Windows端读取出现问题
 
**系统**
（两台电脑）
Microsoft Windows 10 Pro for Workstations 21H1 x64
Microsoft Windows Server 2012 R2 Datacenter x64

**问题复现**
首先就是在我的两台支持虚拟化的Windows电脑均无法正确读取虚拟化情况，在另外一台Linux服务器能够读取虚拟化情况
![image](https://github.com/user-attachments/assets/7b9f122b-e56e-4886-bca8-1af53efc4ae6)
![image](https://github.com/user-attachments/assets/2b287d73-6fea-436c-8ce5-695617f03f2a)
![image](https://github.com/user-attachments/assets/8e993c96-fb4e-4988-b55b-0231ff253998)
然后就是CPU缓存读取错误：
![image](https://github.com/user-attachments/assets/b8d4ab9c-03a1-417c-89a8-5688c8ffed90)
这里电脑2读取L3缓存没有出现错误，但是读取L1缓存依旧错误
硬盘没有测试
![image](https://github.com/user-attachments/assets/778eca19-c1b0-497a-9e81-7a3506dfa867)

**生成文件**
[电脑1goecs.txt](https://github.com/user-attachments/files/16390823/1goecs.txt)
[电脑2goecs.txt](https://github.com/user-attachments/files/16390826/2goecs.txt)
这里云端文件我这里无法访问，所以我自己上传在了gitcode
![image](https://github.com/user-attachments/assets/21ff0136-31ca-4058-8e99-02d335ba08fe)
[电脑1goecs(gitcode).txt](https://gitcode.net/SDCOM_0415/img/-/raw/master/pictures/2024/07/26/18_41_4_goecs.txt)
[电脑2goecs(gitcode).txt](https://gitcode.net/SDCOM_0415/img/-/raw/master/pictures/2024/07/26/18_49_47_goecs.txt)

**Comment by spiritLHLS** [comment]
是云服务器吗？还是本地的物理机器

**Comment by spiritLHLS** [comment]
Windows电脑均无法正确读取可能和注册表有关，我使用读取的注册表获取的信息

你在管理员模式下的PowerShell试试

```
wmic cpu get VirtualizationFirmwareEnabled
```

```
Get-WmiObject -Query "Select * from Win32_CacheMemory"
```

看看有没有输出

**Comment by SDCOM-0415** [comment]
> 是云服务器吗？还是本地的物理机器

是本地的机器

**Comment by spiritLHLS** [comment]
> > 是云服务器吗？还是本地的物理机器
> 
> 是本地的机器

winsat没输出，感觉上是没用管理员模式运行

**Comment by SDCOM-0415** [comment]
> Windows电脑均无法正确读取可能和注册表有关，我使用读取的注册表获取的信息
> 
> 你在管理员模式下的PowerShell试试
> 
> ```
> wmic cpu get VirtualizationFirmwareEnabled
> ```
> 
> ```
> Get-WmiObject -Query "Select * from Win32_CacheMemory"
> ```
> 
> 看看有没有输出

![image](https://github.com/user-attachments/assets/4f3a613e-8e54-4ea2-a79f-6a91ece6de11)
![image](https://github.com/user-attachments/assets/2517a11f-8382-485b-9785-b47d88b10379)
都有输出

**Comment by SDCOM-0415** [comment]
> > > 是云服务器吗？还是本地的物理机器
> > 
> > 
> > 是本地的机器
> 
> winsat没输出，感觉上是没用管理员模式运行

使用的管理员运行

**Comment by SDCOM-0415** [comment]
> > > > 是云服务器吗？还是本地的物理机器
> > > 
> > > 
> > > 是本地的机器
> > 
> > 
> > winsat没输出，感觉上是没用管理员模式运行
> 
> 使用的管理员运行

我再用管理员运行试试看

**Comment by SDCOM-0415** [comment]
![image](https://github.com/user-attachments/assets/1f80a83e-71b8-4aa5-b91b-9182a1ef7ebf)
依旧是读取错误
[goecs.txt](https://github.com/user-attachments/files/16391935/goecs.txt)

**Comment by SDCOM-0415** [comment]
![image](https://github.com/user-attachments/assets/c8c3a020-ff28-4e7a-9618-b8bd64d408f8)
[goecs.txt](https://github.com/user-attachments/files/16391945/goecs.txt)
而且硬盘数据也读错了
![image](https://github.com/user-attachments/assets/dd9aca9b-1506-434f-8054-6f44cc6e293a)

**Comment by spiritLHLS** [comment]
大概知道什么问题了，明天之前会更新依赖 https://github.com/oneclickvirt/basics 进行修复，你明天有空用这个仓库的测测就知道了

**Comment by SDCOM-0415** [comment]
ok

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/basics/releases/download/output/basics-windows-amd64

> ok

尝试修复了一下，我测试了我的电脑没问题，你看看你的

**Comment by SDCOM-0415** [comment]
> https://github.com/oneclickvirt/basics/releases/download/output/basics-windows-amd64
> 
> > ok
> 
> 尝试修复了一下，我测试了我的电脑没问题，你看看你的

测试完了，管理员运行一样的
![image](https://github.com/user-attachments/assets/429319e8-0eed-4bae-993e-757d7de6b0ef)
![image](https://github.com/user-attachments/assets/ee692a17-a2b6-4623-a02e-20a8b51d3f26)
然后就是server2012的机子的硬盘空间依旧是错误的

**Comment by spiritLHLS** [comment]
> > https://github.com/oneclickvirt/basics/releases/download/output/basics-windows-amd64
> > > ok
> > 
> > 
> > 尝试修复了一下，我测试了我的电脑没问题，你看看你的
> 
> 测试完了，管理员运行一样的 ![image](https://private-user-images.githubusercontent.com/127208666/352691275-429319e8-0eed-4bae-993e-757d7de6b0ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNDc1MDEsIm5iZiI6MTcyMjA0NzIwMSwicGF0aCI6Ii8xMjcyMDg2NjYvMzUyNjkxMjc1LTQyOTMxOWU4LTBlZWQtNGJhZS05OTNlLTc1N2Q3ZGU2YjBlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwMjI2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjUwYzNhNTc2MTM0ZmVjYTVhMjQ0MjMzMzY5OGE0YzQ4NGMyNzc1MTkzYzgxYTJlYmEwMTllZjllMTc3OTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mGV2mL2MWinCtEeGA-Z6Ps031_cu-4eJN394V9VemnY) ![image](https://private-user-images.githubusercontent.com/127208666/352691294-ee692a17-a2b6-4623-a02e-20a8b51d3f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNDc1MDEsIm5iZiI6MTcyMjA0NzIwMSwicGF0aCI6Ii8xMjcyMDg2NjYvMzUyNjkxMjk0LWVlNjkyYTE3LWEyYjYtNDYyMy1hMDJlLTIwYThiNTFkM2YyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwMjI2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDk5ZjE2NDMzZDRjZDM5M2EzNzRiNDVmYTQwYmMxODEwMDc2NTBjM2VmNDQxYWY0MWIxNTk1ZDdjMmI3NjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PORoAePxjI6tCVGs707LEDNpYFGvOR73F8W0nPZMk4o) 然后就是server2012的机子的硬盘空间依旧是错误的

不是，我是说用 https://github.com/oneclickvirt/basics/releases/download/output/basics-windows-amd64 进行测试，我还没更新GO版本的融合怪，所以当然一样啦

现在我更新了GO版本的融合怪，你跑哪个测都行了

**Comment by SDCOM-0415** [comment]
行
