### ISSUE TITLE
[建议] 在执行 update 等关键操作前进行用户确认

### ISSUE THREAD

**Issue by lslqtz** [oneclickvirt/ecs#5]
```(yum / apt-get) update``` 是具有风险性的关键操作, 不仅执行缓慢, 还可能导致 网络短暂掉线 / 服务器卡死 / 下次无法启动 等非预期危害, 这一操作在 ```goecs.sh env``` 期间被执行, 且在 shell 脚本说明中仅提到其"检查并安装包".

通过在执行前加入用户确认 (并/或 优化 shell 脚本说明) 可以让用户知晓此操作的风险. 由于 shell 脚本中对此项的依赖仅为编译 sysbench, 因此用户拒绝确认时, 还可以考虑跳过此项功能的支持.

**Comment by lslqtz** [comment]
经过查询, 我遇到的问题似乎为 yum 安装 epel-release 导致的卡死, 并有概率造成进程卡死/服务器掉线/服务器卡死 (小内存机器尤为显著, 低内存使关键进程如 sshd 被 kill), 这一进程卡死可能是造成我使用的支持 OS (AlmaLinux) 降级为编译安装的原因. 由于安装 epel-release 导致的卡死可能会影响 yum 后续的正常工作, 因此对小内存机器可能也需要进行确认, 并可能还需要一个回退处理 (https://stackoverflow.com/a/61689375, ```rm -f /etc/yum.repos.d/*epel* && yum clean all```).

一般认为, epel 最低需求内存为 2GB, 实际虽然 512MB 较为罕见, 但 1GB 内存对于转发及落地仍是较好的使用场景.

**Comment by spiritLHLS** [comment]
多谢提醒，我今日内会更新相关部分代码加上说明和选择，避免而类似问题再次发生

**Comment by spiritLHLS** [comment]
Fixed.
